[package]
name = "simd-chess"
version = "0.1.0"
edition = "2024"

[dependencies]
pollster = "0.4.0"
wgpu = "25.0.2"
image = { version = "0.24", features = ["png"] }
clipboard = "0.5.0"
rand = "0.9.1"
anyhow = "1.0.98"
crossbeam = "0.8.4"
core_affinity = "0.8.3"
sfbinpack = { version = "0.4.3", features = ["bmi2"] }
bullet = { git = "https://github.com/jw1912/bullet", rev = "cebc78a", package = "bullet_lib", features = [
    "cuda",
] }
zstd = "0.13.3"
llvm-mca = "0.1.0"

[profile.release]
debug = true
lto = "fat"
panic = "abort"
codegen-units = 1
# debug-assertions = true
